[package]
name = "mineshake"
version = "0.1.1"
authors = ["Syfaro <syfaro@huefox.com>"]
edition = "2018"

[dependencies]
resolve = "0.2"
rand = "0.7"

serde = { version = "1", features = ["derive"] }
serde_json = "1"

tokio = { version = "0.2", features = ["macros", "net", "tcp", "io-util"] }
